### ISSUE TITLE
Brother MFC-1810 work

### ISSUE THREAD

**Issue by MrDuartePT** [pdewacht/brlaser#148] opened 2022-01-05 19:47 UTC
I use the driver of MFC-1910w and work with mfc-1810 before use I make a research and find out the two printer are identical the mfc-1910w as Wi-Fi and mobile app.

Output of the command:![image](https://user-images.githubusercontent.com/68701049/148279869-61849270-36ad-4b1b-be5e-d3ebb1d9f520.jpeg)

Device: uri = usb://Brother/MFC-1810%20series?serial=E72371M3N791587
        class = direct
        info = Brother MFC-1810 series
        make-and-model = Brother MFC-1810 series
        device-id = MFG:Brother;CMD:PJL,XL2HB;MDL:MFC-1810 series;CLS:PRINTER;CID:Brother Laser Type1;
        location = 

Note:For all that find this issue and the the support isn't add use MFC-1910W driver with the default settings (I don't try the other settings like toner saver and others).

**Comment by zeroheure** [comment] 2022-01-06 17:01
duplicate of #148

**Closed** 2022-01-17 13:14 UTC
