### ISSUE TITLE
Add HL-L2390DW to Supported List

### ISSUE THREAD

**Issue by clairmont32** [pdewacht/brlaser#96] opened 2020-11-29 03:51 UTC
Hello,

I was successful in printing with this device on my Pi after selecting the driver `Brother DCP-7030, using brlaser v3 (grayscale)` since it was the first in the CUPS list.

`Device: uri = usb://Brother/HL-L2390DW?serial=<SN Here>
        class = direct
        info = Brother HL-L2390DW
        make-and-model = Brother HL-L2390DW
        device-id = MFG:Brother;CMD:PJL,HBP,URF;MDL:HL-L2390DW;CLS:PRINTER;CID:Brother Laser Type1;URF:W8,CP1,IS4-1,MT1-3-4-5-8,OB10,PQ3-4-5,RS300-600-1200,V1.4,DM1;
        location =
`

Thank you for making this super easy!

**Comment by QORTEC** [comment] 2021-03-15 04:52
Duplicate of #62 and Closed by eae5f9ba98d48901638fc226777825805d734ade
Your Printer ``HL-L2390DW`` is already officially supported, and drivers should be available in ``brlaser v6``.
Try looking for updates, if there are none then request the distribution to updated ``brlaser`` form version ``3`` to ``6`` in their repositories.

**Closed** 2021-06-13 16:06 UTC
